# Generated by Django 3.0.6 on 2020-06-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elective_search', '0003_auto_20200622_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewerATLASSemester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6')], max_length=1),
        ),
    ]
