# Generated by Django 3.0.6 on 2020-06-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elective_search', '0005_auto_20200624_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Published',
            field=models.BooleanField(default=False),
        ),
    ]
