# Generated by Django 3.0.6 on 2020-06-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elective_search', '0006_review_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Published',
            new_name='published',
        ),
    ]
