# Generated by Django 3.0.5 on 2020-05-15 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('osirisCode', models.IntegerField()),
                ('numberOfECs', models.DecimalField(decimal_places=1, max_digits=3)),
                ('electiveType', models.CharField(choices=[('UT', 'Course at the UT'), ('MOD', 'Full module at the UT'), ('ONLINE', 'Online Course'), ('OTHER', '')], max_length=6)),
                ('language', models.CharField(choices=[('NL', 'Dutch'), ('EN', 'English')], max_length=2)),
                ('utBlock', models.CharField(choices=[('1A', 'Quartile 1'), ('1B', 'Quartile 2'), ('2A', 'Quartile 3'), ('2B', 'Quartile 4')], max_length=2)),
                ('entryRequirements', models.TextField()),
                ('contactPersonName', models.CharField(max_length=35)),
                ('contactPersonEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewerName', models.CharField(max_length=35)),
                ('reviewerEmail', models.EmailField(max_length=254)),
                ('reviewerATLASSemester', models.CharField(choices=[('1', 'Semester1'), ('2', 'Semester2'), ('3', 'Semester3'), ('4', 'Semester4'), ('5', 'Semester5'), ('6', 'Semester6')], max_length=1)),
                ('overallScore', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('overallScoreExplanation', models.CharField(max_length=250)),
                ('prerequisiteKnowledge', models.CharField(max_length=250)),
                ('challengingScore', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('challengingScoreExplanation', models.CharField(max_length=250)),
                ('workloadScore', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('workloadScoreExplanation', models.CharField(max_length=250)),
                ('additionalComments', models.CharField(max_length=250)),
                ('elective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electives.Elective')),
            ],
        ),
    ]
