# Generated by Django 3.0.6 on 2020-06-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0002_auto_20200515_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elective',
            name='electiveType',
            field=models.CharField(choices=[('UT', 'Course at the UT'), ('MODULE', 'Full module at the UT'), ('ONLINE', 'Online Course'), ('OTHER', 'Other')], max_length=6),
        ),
    ]
