# Generated by Django 3.0.6 on 2020-06-23 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments_section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('slug', models.SlugField(default='', max_length=250, unique=True)),
                ('content', models.TextField(default='')),
                ('seo_title', models.CharField(default='', max_length=250)),
                ('seo_description', models.CharField(default='', max_length=160)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
